[political_democracy]
git-tree-sha1 = "a02b07e3523570d8a27c9fe10dcac3a1e4705c33"
lazy = true

    [[political_democracy.download]]
    sha256 = "a0863116c7cd4de04a705ebd6603eef01d47c497170c452c27aabde45e902cde"
    url = "https://github.com/StructuralEquationModels/Data/tree/main/datasets/political_democracy/compressed/data.csv.tar.gz"
