[political_democracy]
git-tree-sha1 = "a02b07e3523570d8a27c9fe10dcac3a1e4705c33"
lazy = true

    [[political_democracy.download]]
    sha256 = "e8b4d62067923d36d232e1e356d3634ff3942353cfe080f10699467260af2652"
    url = "https://github.com/StructuralEquationModels/Data/raw/b29d2da78e5e9abc9bda101bde9a1bf4c4b2b98b/datasets/political_democracy/compressed/data.csv.tar.gz"

[political_democracy_solution]
git-tree-sha1 = "6d86194bc13aa01eb3cf92a3aad834110432481c"
lazy = true

    [[political_democracy_solution.download]]
    sha256 = "f10127beda2bc29eacd6d26e1be8d32fa6f1527ccc0a0f4b3970c4ee328970bb"
    url = "https://github.com/StructuralEquationModels/Data/raw/f0673213071885ce43df566ec68dfce5821c8409/datasets/political_democracy/compressed/political_democracy_solution.tar.gz"
